export const SUCCESS = 0
export const CLI_BAD_STARTUP_ARGUMENT = 100
export const RPC_EXCEPTION = 101
export const CLI_BAD_REGISTER_PROFILE_ARGUMENT = 102
export const CLI_BAD_UPDATE_PROFILE_ARGUMENT = 103
export const NO_ONCHAIN_PROFILE = 200